### PR TITLE
update doc with aks auth details

### PR DESCRIPTION
**Pull request by sudivate**
#227

### CODE REVIEW

**Comment by sudivate** [comment]
#227

**Comment by dtzar** [comment]
Looking at the reference doc on how to do the authentication, it will likely take people some time to figure out to properly connect.  Why not just disable the authentication by default and suggest people to enable it for production implementations?

**Comment by sudivate** [comment]
> Looking at the reference doc on how to do the authentication, it will likely take people some time to figure out to properly connect. Why not just disable the authentication by default and suggest people to enable it for production implementations?

Auth is enabled by default unless explicitly suppressed at the time of model deployment. Its good to keep it enabled as a best security practice. Existing smoke test for model post-deployment shows how to access service with auth.

**Comment by dtzar** [comment]
Makes sense - I'd call out the line(s) of code the smoke test uses in the doc and we're good.

**Comment by sudivate** [comment]
> Makes sense - I'd call out the line(s) of code the smoke test uses in the doc and we're good.

Thank you . Done !

**Pull request merged**
