### PR TITLE
Rename pipeline YAMLs for clarity

### PR DESCRIPTION
**Pull request by tcare**
Renamed pipelines to a more uniform structure.
- Templates have a -template suffix.
- base is renamed to code-quality to better reflect its functionality
- -build-train has been removed from CI/PR since those do more than build and train now.

### CODE REVIEW

**Comment by algattik** [comment]
Could we also take the opportunity to remove the dot in ".pipelines"? That is really confusing at it looks to user like a derived folder more than part of source control, and does not appear in some UIs. I don't see the point of "hiding" the pipelines in a project whose very focus is devops.

**Comment by tcare** [comment]
@dtzar @jotaylo thoughts on @algattik's suggestion?

**Comment by tcare** [comment]
@jotaylo created a temporary pipeline to test the PR, the passing job is at https://aidemos.visualstudio.com/MLOps/_build/results?buildId=3966

**Comment by dtzar** [comment]
@algattik @tcare `.pipelines` folder was used because this was a similar folder structure used for other similar orchestrator pipeline products.  i.e. Github workflows uses `.gihub\workflow` CircleCI uses `.circleci`

**Comment by dtzar** [comment]
I agree though that `.pipelines` is ambiguous.  The official name for these are "Azure Pipelines" although a folder like `.azurepipelines` or `.azure` seems no better.  Open to other ideas, but IMO all the pipelines orchestration should be contained in a folder at the root.  Not stuck on the `.` at the start, although I like this puts the folder at the top of the order and as mentioned it seems to be a common pattern.

**Comment by tcare** [comment]
We'll merge for now and can do another PR if we feel strongly about changing the folder.

**Comment by tcare** [comment]
Pipelines have all been updated, let me know if you see issues :)

**Pull request merged**
