### PR TITLE
remove file_name argument because it's not used in function

### PR DESCRIPTION
**Pull request by cindyweng**

### CODE REVIEW

**Comment by cindyweng** [comment]
Leaving "file_name" argument in also causes the AML pipeline to fail because elsewhere in the CI pipeline, the function is called without a filename argument, and throws an error.

**Comment by martin-weber** [comment]
I was running into the same issue, see #253 .
Another solution would be to switch lines for the file_name assignment and then call create_sample_data_csv(file_name) as described in #253 . And replace the constant file_name in df.to_csv(...):

```python
import pandas as pd
from sklearn.datasets import load_diabetes

# Loads the diabetes sample data from sklearn and produces a csv file that can
# be used by the build/train pipeline script.
def create_sample_data_csv(file_name):
    sample_data = load_diabetes()
    df = pd.DataFrame(
        data=sample_data.data,
        columns=sample_data.feature_names)
    df['Y'] = sample_data.target
    # Hard code to diabetes so we fail fast if the project has been
    # bootstrapped.
    df.to_csv(file_name, index=False)
```

**Comment by cindyweng** [comment]
@martin-weber I looked into those changes but chose this solution purely because it was fewer code edits and didn't seem to bork anything :)

**Comment by martin-weber** [comment]
@cindyweng Fine for me. Both solutions work.

**Pull request merged**
